name: hf-audio-stem
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # 1. Le cœur du système (On fixe juste Python et la version de CUDA compatible avec ton PC)
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  
  # 2. Les exécutables système indispensables pour l'audio
  - ffmpeg
  - ffmpeg-python
  
  # 3. On appelle pip pour le reste
  - pip
  - pip:
      # --- Audio & Traitement de signal ---
      - librosa
      - musdb
      - stempeg
      - pydub
      - soundfile
      
      # --- Data Science & Machine Learning ---
      - pandas
      - scipy
      - scikit-learn
      - matplotlib
      
      # --- Hugging Face & IA ---
      - transformers
      - datasets
      - huggingface-hub
      - gradio
      
      # --- Outils de développement ---
      - jupyterlab
      - ipykernel